---
# handlers file for cadvisor

- name: restart cadvisor
  community.docker.docker_container:
    name: cadvisor
    state: started
    restart: true

- name: reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when: ansible_os_family == "RedHat"
