---
galaxy_info:
  author: FABRIC Team
  description: Install and configure Prometheus Node Exporter
  company: FABRIC
  
  license: MIT
  
  min_ansible_version: "2.9"
  
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  
  galaxy_tags:
    - monitoring
    - prometheus
    - metrics
    - observability
    - fabric

dependencies: []
