---
# vars file for docker - Debian family

docker_repo_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
docker_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_apt_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"
