---
# Sample playbook for FABRIC slice management
- name: Configure all nodes
  hosts: all_nodes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    
    - name: Install common packages
      apt:
        name:
          - vim
          - htop
          - curl
          - wget
          - net-tools
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Ensure hostname is set correctly
      hostname:
        name: "{{ inventory_hostname }}"
    
    - name: Display node information
      debug:
        msg: "Node {{ inventory_hostname }} at {{ ansible_host }}"

- name: Configure OpenStack control nodes
  hosts: openstack_control
  become: yes
  tasks:
    - name: Display control node info
      debug:
        msg: "This is an OpenStack control node"

- name: Configure OpenStack compute nodes
  hosts: openstack_compute
  become: yes
  tasks:
    - name: Display compute node info
      debug:
        msg: "This is an OpenStack compute node"

